"""second migration

Revision ID: fc63313f6365
Revises: 8c913e5b91d3
Create Date: 2024-10-28 22:48:26.759509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc63313f6365'
down_revision = '8c913e5b91d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medspa_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'medspa', ['medspa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('medspa_id')

    # ### end Alembic commands ###
